### ISSUE TITLE
Mac OS X launching process as x64

### ISSUE THREAD

**Issue by thefiddler** [OutOfOrder/MonoKickstart#1]
Originally reported here: http://www.opentk.com/node/3627#comment-15511

While debugging some strange crashes with MonoKickstart on Mac OS X, it was revealed that MonoKickstart is launching mono as a x64 process. This is not (yet) officially supported by the Mono runtime, and it's causing various failures related to ABI mismatches and missing libraries (e.g. there is no x64 version of libgdiplus.)

Is there a way to launch MonoKickstart as a x86 process on Mac OS X?

**Comment by flibitijibibo** [comment]
You can remove the 64-bit bins with 'lipo' on OSX.
