### ISSUE TITLE
updated to Mono 3.12

### ISSUE THREAD

**Issue by urkle** [OutOfOrder/MonoKickstart#2]

**Comment by PumpkinPaul** [comment]
Hi Edward - is there any news on a fix for this issue? I've just update to Mono 3.12.0 and it's broken my MonoKickstart :-( I'm getting a the following error while trying to execute my app...

Library not loaded: /usr/local/lib/libmono-2.0.1.dylib
  Referenced from: /blahblahblah/MyApp.app/Contents/MacOS/./MyApp.bin.osx
  Reason: no suitable image found.  Did find:
    ./osx//libmono-2.0.1.dylib: mach-o, but wrong architecture

Kind regards,
Paul

**Comment by flibitijibibo** [comment]
Sounds like it's just missing an architecture - `file` should be able to say which architectures are found for both the executable and the library. May be worth checking the SDK version that it was targeting as well, if this fails for a specific OSX version (should be 10.6).

**Comment by PumpkinPaul** [comment]
Checking the mono framework folders for 2.10.9 and 3.12.0, lipo -info libmono-2.0.dylib displays i386. Whereas it's x86_64 i386 in my kickstarts that work. However, as I've upgraded Xamarin Studio I can't use the old mono dlls / libs.

**Comment by flibitijibibo** [comment]
That's probably it then - we build universal binaries since self-building Mono lets us do 64-bit builds as well (as long as it's not SGen), so you'll need to edit CMakeLists.txt and remove the x86_64 build.

(Also, when is Xamarin finishing that 64-bit support they said they would add?)

**Comment by PumpkinPaul** [comment]
Ah, never used MAKE. I naively thought I could just make -FCMakeList.txt :-)
Is there a way to just copy the latest (32bit) libs from the 3.12.0 framework into the Mac bundle folder and tell the kickstart to force to 32bit?

**Comment by flibitijibibo** [comment]
`lipo -extract` should let you remove architectures from a universal binary.

**Comment by urkle** [comment]
OR you can simply set the LSArchitecturePriority info.plist property to an array of just i386.  https://developer.apple.com/library/ios/documentation/General/Reference/InfoPlistKeyReference/Articles/LaunchServicesKeys.html#//apple_ref/doc/uid/TP40009250-106825-TPXREF124

**Comment by tomrijnbeek** [comment]
I am having some problems getting the 3.12 version to work on OSX. When copying the files first time, I got the error that the `mscorlib.dll` was out of sync, so I copied it (together with `libmono.dylib`) from my own Mono.framework (at version 3.12.1). It then complains about the architecture for the `libmono.dylib`, so I used `lipo` to extract the x64 architecture from the `bin.osx` file.

The error I then get is

```
dyld: Symbol not found: _kCFLocaleCountryCode
  Referenced from: {app}/Contents/MacOS/osx/libmono-2.0.1.dylib
  Expected in: flat namespace
 in {app}/Contents/MacOS/osx/libmono-2.0.1.dylib
./rochefusion: line 24:  2329 Trace/BPT trap: 5       ./${BASENAME}.bin.${ext} $@
```

From some Googling it appears that since Mono 3.4 you have to link the mono binary to the CoreFoundation framework. Sadly I do not understand the code well enough to make changes myself (I can't even get things to compile myself), so I figured I would let you know about this. Maybe the problem lies with me replacing the included `libmono.dylib`, but as mentioned, it seems to be out of sync with the `mscorlib.dll` distributed:

```
Corlib not in sync with this runtime: expected corlib version 96, found 111.
Loaded from: {app}/Contents/MacOS/mscorlib.dll
Download a newer corlib or a newer runtime at http://www.go-mono.com/daily.
```

**Comment by flibitijibibo** [comment]
Worse comes to worse, use my 2.10.9 branch over here:

https://github.com/flibitijibibo/MonoKickstart

We'll probably update to 4.0.1 at some point given the .NET Core stuff going on, but that get put off depending on what surrounding projects need.

Will also have to figure out why it doesn't link the dylib properly; this comes straight from their build environment!

**Comment by tomrijnbeek** [comment]
I am afraid that our engine (we do not use MonoGame) does not support mono versions that old, but thanks for the pointer! I will be keeping an eye on this repository for a solution. Let me know if you need my help to test anything.

**Comment by flibitijibibo** [comment]
Fair enough! If you end up giving kick.c a try with 4.0.1, let us know and we might be able to patch that into upstream (though prebuilt might still be done on Edward's CentOS box for Linux, for a nice low glibc requirement).

**Comment by PumpkinPaul** [comment]
I'm pretty sure I was able to work round this issue in the end. I think I rolled the mono version back either by hacking the project file or using a different project type and changing the default framework back to the previous version

**Comment by flibitijibibo** [comment]
Closing this for a 4.x issue...
